# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-14 16:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='follow_targets',
            field=models.ManyToManyField(related_name='followers', to='profiles.Profile'),
        ),
    ]
