# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-14 17:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='name',
            field=models.CharField(default='Anonymous User', max_length=200),
            preserve_default=False,
        ),
    ]
