languages:
  Ruby: true
  JavaScript: true
  PHP: true
  Python: true
exclude_paths:
- "divesites/tests/test_views.py"
- "divesites/migrations/**/*"
- "divesites/tests/**/*"
- "myauth/migrations/**/*"
- "myauth/tests/**/*"
- "profiles/migrations/**/*"
- "profiles/tests/**/*"
- "activity/migrations/**/*"
- "activity/tests/**/*"
