language: python
python:
  - 3.5
services:
  - postgresql
addons:
  postgresql: "9.4"
install:
  - pip install -r requirements.txt
  - pip install coveralls
script:
  coverage run --source='.' manage.py test -v 2
after_success: 
  - coveralls
