# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-09 15:26
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('divesites', '0009_auto_20160208_1546'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='CompressorComment',
            fields=[
                ('comment_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='comments.Comment')),
                ('compressor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='divesites.Compressor')),
            ],
            bases=('comments.comment',),
        ),
        migrations.CreateModel(
            name='DivesiteComment',
            fields=[
                ('comment_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='comments.Comment')),
                ('divesite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='divesites.Divesite')),
            ],
            bases=('comments.comment',),
        ),
        migrations.CreateModel(
            name='SlipwayComment',
            fields=[
                ('comment_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='comments.Comment')),
                ('slipway', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='divesites.Slipway')),
            ],
            bases=('comments.comment',),
        ),
        migrations.AddField(
            model_name='comment',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL),
        ),
    ]
