# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-17 15:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    def fix_comment_verbs(apps, schema_editor):
        Action = apps.get_model('actstream', 'Action')
        for action in Action.objects.all():
            if action.verb == 'commented on':
                action.verb = 'commented'
                action.save()

    def rollback(apps, schema_editor):
        Action = apps.get_model('actstream', 'Action')
        for action in Action.objects.all():
            if action.verb == 'commented':
                action.verb = 'commented on'
                action.save()


    dependencies = [
        ('comments', '0003_auto_20160217_1330'),
    ]

    operations = [
            migrations.RunPython(fix_comment_verbs, rollback)
    ]
