# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-24 16:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0003_auto_20160224_1646'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='compressorimage',
            name='baseimage_ptr',
        ),
        migrations.RemoveField(
            model_name='compressorimage',
            name='compressor',
        ),
        migrations.RemoveField(
            model_name='divesiteimage',
            name='baseimage_ptr',
        ),
        migrations.RemoveField(
            model_name='divesiteimage',
            name='divesite',
        ),
        migrations.RemoveField(
            model_name='slipwayimage',
            name='baseimage_ptr',
        ),
        migrations.RemoveField(
            model_name='slipwayimage',
            name='slipway',
        ),
        migrations.DeleteModel(
            name='CompressorImage',
        ),
        migrations.DeleteModel(
            name='DivesiteImage',
        ),
        migrations.DeleteModel(
            name='SlipwayImage',
        ),
    ]
