# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-14 17:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0004_auto_20160224_1652'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='baseimage',
            name='owner',
        ),
        migrations.DeleteModel(
            name='BaseImage',
        ),
    ]
