# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-21 19:31
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('activity', '0002_auto_20151221_1901'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc', models.TextField(blank=True)),
                ('creation_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='divelog',
            name='creation_date',
        ),
        migrations.RemoveField(
            model_name='divelog',
            name='desc',
        ),
        migrations.RemoveField(
            model_name='divelog',
            name='id',
        ),
        migrations.RemoveField(
            model_name='divelog',
            name='user',
        ),
        migrations.RemoveField(
            model_name='divesitecreation',
            name='creation_date',
        ),
        migrations.RemoveField(
            model_name='divesitecreation',
            name='desc',
        ),
        migrations.RemoveField(
            model_name='divesitecreation',
            name='id',
        ),
        migrations.RemoveField(
            model_name='divesitecreation',
            name='user',
        ),
        migrations.AddField(
            model_name='divelog',
            name='activity_ptr',
            field=models.OneToOneField(auto_created=True, default=None, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='activity.Activity'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='divesitecreation',
            name='activity_ptr',
            field=models.OneToOneField(auto_created=True, default=None, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='activity.Activity'),
            preserve_default=False,
        ),
    ]
