# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-27 14:37
from __future__ import unicode_literals

import divesites.validators
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Compressor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('latitude', models.DecimalField(decimal_places=12, max_digits=15, validators=[divesites.validators.validate_latitude])),
                ('longitude', models.DecimalField(decimal_places=12, max_digits=15, validators=[divesites.validators.validate_longitude])),
                ('creation_data', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compressors', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Dive',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('comment', models.TextField(blank=True)),
                ('depth', models.DecimalField(decimal_places=1, max_digits=4)),
                ('duration', models.DurationField()),
                ('start_time', models.DateTimeField()),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('diver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dives', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['start_time'],
            },
        ),
        migrations.CreateModel(
            name='Divesite',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('boat_entry', models.BooleanField(default=True)),
                ('shore_entry', models.BooleanField(default=True)),
                ('level', models.SmallIntegerField(choices=[(0, 'Beginner'), (1, 'Intermediate'), (2, 'Advanced')])),
                ('latitude', models.DecimalField(decimal_places=12, max_digits=15, validators=[divesites.validators.validate_latitude])),
                ('longitude', models.DecimalField(decimal_places=12, max_digits=15, validators=[divesites.validators.validate_longitude])),
                ('geocoding_data', models.TextField(blank=True)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='divesites', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Slipway',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('latitude', models.DecimalField(decimal_places=12, max_digits=15, validators=[divesites.validators.validate_latitude])),
                ('longitude', models.DecimalField(decimal_places=12, max_digits=15, validators=[divesites.validators.validate_longitude])),
                ('creation_data', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slipways', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='dive',
            name='divesite',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dives', to='divesites.Divesite'),
        ),
    ]
