# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-13 15:08
from __future__ import unicode_literals

import divesites.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Dive',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('duration', models.DurationField()),
                ('start_time', models.DateTimeField()),
                ('diver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Divesite',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('latitude', models.DecimalField(decimal_places=7, max_digits=10, validators=[divesites.models.validate_latitude])),
                ('longitude', models.DecimalField(decimal_places=7, max_digits=10, validators=[divesites.models.validate_longitude])),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='dive',
            name='divesite',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='divesites.Divesite'),
        ),
    ]
