# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-14 12:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('divesites', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='divesite',
            name='level',
            field=models.SmallIntegerField(choices=[(0, 'Beginner'), (1, 'Intermediate'), (2, 'Advanced')], default=1),
            preserve_default=False,
        ),
    ]
