# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-14 12:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('divesites', '0002_divesite_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='divesite',
            name='boat_entry',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='divesite',
            name='shore_entry',
            field=models.BooleanField(default=True),
        ),
    ]
