# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-04 16:58
from __future__ import unicode_literals

import divesites.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('divesites', '0002_auto_20160128_0053'),
    ]

    operations = [
        migrations.AddField(
            model_name='compressor',
            name='geocoding_data',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='slipway',
            name='geocoding_data',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='compressor',
            name='latitude',
            field=models.DecimalField(decimal_places=20, max_digits=23, validators=[divesites.validators.validate_latitude]),
        ),
        migrations.AlterField(
            model_name='compressor',
            name='longitude',
            field=models.DecimalField(decimal_places=20, max_digits=23, validators=[divesites.validators.validate_longitude]),
        ),
        migrations.AlterField(
            model_name='slipway',
            name='latitude',
            field=models.DecimalField(decimal_places=20, max_digits=23, validators=[divesites.validators.validate_latitude]),
        ),
        migrations.AlterField(
            model_name='slipway',
            name='longitude',
            field=models.DecimalField(decimal_places=20, max_digits=23, validators=[divesites.validators.validate_longitude]),
        ),
    ]
