# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-14 14:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('divesites', '0003_auto_20151214_1253'),
    ]

    operations = [
        migrations.AddField(
            model_name='divesite',
            name='depth',
            field=models.FloatField(default=50),
            preserve_default=False,
        ),
    ]
