# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-17 16:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('divesites', '0003_auto_20160113_1326'),
    ]

    operations = [
        migrations.AddField(
            model_name='divesite',
            name='geocoding_data',
            field=models.TextField(blank=True),
        ),
    ]
