# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-08 11:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('divesites', '0003_auto_20160204_1658'),
    ]

    operations = [
        migrations.AddField(
            model_name='dive',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dive',
            name='time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
