# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-14 15:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('divesites', '0004_divesite_depth'),
    ]

    operations = [
        migrations.AddField(
            model_name='dive',
            name='comment',
            field=models.TextField(default='Inventore sed voluptatum labore non doloribus.'),
            preserve_default=False,
        ),
    ]
