# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-08 11:05
from __future__ import unicode_literals
import datetime

from django.db import migrations
from django.utils import timezone

def split_datetime(apps, schema_editor):
    Dive = apps.get_model('divesites', 'Dive')
    for dive in Dive.objects.all():
        st = dive.start_time
        dive.date = datetime.date(year=st.year, month=st.month, day=st.day)
        dive.time = timezone.make_aware(datetime.time(hour=st.hour, minute=st.minute, second=st.second), timezone=st.tzinfo)
        dive.save()

class Migration(migrations.Migration):


    dependencies = [
        ('divesites', '0004_auto_20160208_1102'),
    ]

    operations = [
            migrations.RunPython(split_datetime)
    ]
