# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-14 15:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('divesites', '0005_dive_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='dive',
            name='depth',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=4),
            preserve_default=False,
        ),
    ]
