# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-14 15:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('divesites', '0006_dive_depth'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='divesite',
            name='depth',
        ),
    ]
