# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-08 11:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('divesites', '0007_auto_20160208_1131'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dive',
            options={'ordering': ['date', 'time']},
        ),
        migrations.RemoveField(
            model_name='dive',
            name='start_time',
        ),
    ]
