# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-14 16:04
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('divesites', '0007_remove_divesite_depth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dive',
            name='diver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dives', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='dive',
            name='divesite',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dives', to='divesites.Divesite'),
        ),
    ]
