# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-16 12:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('divesites', '0009_auto_20151215_1423'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dive',
            options={'ordering': ['start_time']},
        ),
        migrations.AddField(
            model_name='divesite',
            name='header_image_url',
            field=models.URLField(blank=True),
        ),
    ]
