# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-17 18:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('divesites', '0010_auto_20160215_2345'),
    ]

    operations = [
        migrations.RenameField(
            model_name='compressor',
            old_name='creation_data',
            new_name='creation_date',
        ),
        migrations.RenameField(
            model_name='slipway',
            old_name='creation_data',
            new_name='creation_date',
        ),
    ]
