# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-21 18:54
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('divesites', '0010_auto_20151216_1202'),
    ]

    operations = [
        migrations.AddField(
            model_name='dive',
            name='creation_date',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2015, 12, 21, 18, 53, 56, 672766, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='divesite',
            name='creation_date',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2015, 12, 21, 18, 54, 1, 198071, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='divesite',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='divesites', to=settings.AUTH_USER_MODEL),
        ),
    ]
