# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-06 14:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('divesites', '0011_auto_20160217_1808'),
    ]

    operations = [
        migrations.AddField(
            model_name='dive',
            name='air_temperature',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='dive',
            name='water_temperature',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True),
        ),
    ]
