# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-07 22:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('divesites', '0011_auto_20151221_1854'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='divesite',
            name='header_image_url',
        ),
    ]
