# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-06 15:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('divesites', '0012_auto_20160306_1458'),
    ]

    operations = [
        migrations.AddField(
            model_name='dive',
            name='air_in',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dive',
            name='air_out',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dive',
            name='cylinder_capacity',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True),
        ),
    ]
