# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-11 12:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('divesites', '0013_auto_20160306_1533'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dive',
            old_name='air_in',
            new_name='pressure_in',
        ),
        migrations.RenameField(
            model_name='dive',
            old_name='air_out',
            new_name='pressure_out',
        ),
    ]
