# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-13 17:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('divesites', '0017_dive_wind'),
    ]

    operations = [
        migrations.AddField(
            model_name='dive',
            name='weather',
            field=models.CharField(blank=True, choices=[(('clear',), 'Clear'), (('clouds',), 'Clouds'), (('rain',), 'Rain'), (('fog',), 'Fog'), (('snow',), 'Snow')], max_length=50, null=True),
        ),
    ]
